### ISSUE TITLE
About the [fork]

### ISSUE THREAD

**Issue by dcccd-dd** [zRapha/AIMED#10]
Hello, I clone the project of (https://github.com/SebieF/AIMED), which can run successfully. Howerver, the target model of **lgbm_ember.pkl** gives me a error detect result, which makes me confused. For example, I use a file marked as malware by VirusTotal, but this model only gives a very low score.

thank you for your interest in AIMED-RL and sorry for the delayed response. Unfortunately, there have been some compatibility problems between AIMED-RL and the code of other papers, such as AIMED and ARMED. Hence, please refer to my  [fork](https://github.com/SebieF/AIMED) of this repository, where you can find a working version of AIMED-RL with fixed requirements. The error you encountered is caused by a wrong version of scikit-learn (amongst others). You can also find a more exhaustive description of how-to use AIMED-RL in this [blog article](https://sebief.github.io/it-security/tutorial/aimedRL/). 
If you face any more issues, please let us know!

_Originally posted by @SebieF in https://github.com/zRapha/AIMED/issues/5#issuecomment-981130628_

**Comment by zRapha** [comment]
Duplicated.
