### ISSUE TITLE
about db

### ISSUE THREAD

**Issue by zhang-x-h** [zRapha/AIMED#4]
I wonder if the author could provide the files in DB and the link of where to download the dataset?
thank you!

**Comment by zhang-x-h** [comment]
Hi!


&nbsp; &nbsp;thank you for your reply !
&nbsp; &nbsp;Can the dataset be placed directly in the samples/unzipped folder using the.exe file?&nbsp; &nbsp;Since I don't have virus Total API, I have collected some exe files by myself.&nbsp;
Or are the files in the DB folder generated from the dataset themselves?&nbsp;


best


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zRapha/AIMED"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年10月20日(星期三) 晚上8:29
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [zRapha/AIMED] about db (Issue #4)





 
Hi, the DB is going to be filled depending upon the modules / datasets you choose. Regarding the datasets, I would suggest going for known public sources such as VirusTotal, etc.
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by zRapha** [comment]
Yes, the PE files need to be placed under samples/unzipped. The DBs are generated automatically when you run the environment. They are going to log which file was used, number and sequence of transformations injected, hash of new file, and so on every time you run a module (e.g., ARMED) in three states: evasive, detected or corrupt (the latter if integrity test is implemented).

**Comment by zRapha** [comment]
Close issue due to inactivity.
